dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    // lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // LDLib
    implementation("com.lowdragmc.ldlib:ldlib-neoforge-${minecraft_version}:${ldlib_version}") { transitive = false }

    // JEI
    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}") { transitive = false }
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}") { transitive = false }
    implementation("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    // REI
    compileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin-neoforge:${rei_version}")
    compileOnly("me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei_version}")
    compileOnly("me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}")

    // EMI
    compileOnly("dev.emi:emi-neoforge:${emi_version}:api")
    compileOnly("dev.emi:emi-neoforge:${emi_version}")

    // Geckolib
    implementation("software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}")
    implementation("com.eliotlash.mclib:mclib:20")

    // Photon
    // TODO
//    implementation("com.lowdragmc.photon:photon-forge-${minecraft_version}:${photon_version}") { transitive = false }

    // Botania
//    compileOnly("vazkii.botania:botania-neoforge-${minecraft_version}:${botania_version}:api")
    implementation("vazkii.botania:botania-neoforge-${minecraft_version}:${botania_version}")
    runtimeOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}")
    runtimeOnly("vazkii.patchouli:Patchouli:${patchouli_version}")

    // Mekanism
    compileOnly("mekanism:Mekanism:${mekanism_version}:api")
    implementation("mekanism:Mekanism:${mekanism_version}") // Mekanism
    runtimeOnly("mekanism:Mekanism:${mekanism_version}:additions")// Mekanism: Additions
    runtimeOnly("mekanism:Mekanism:${mekanism_version}:generators")// Mekanism: Generators
    runtimeOnly("mekanism:Mekanism:${mekanism_version}:tools")// Mekanism: Tools

    // GTM
    // TODO
//    compileOnly("com.gregtechceu.gtceu:gtceu-${minecraft_version}:${gtm_version}") { transitive = false }
//    compileOnly("com.tterrag.registrate:Registrate:${registrate_version}")

    // Create
    implementation("com.simibubi.create:create-${minecraft_version}:${create_version}:all") { transitive = false }
    implementation("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    implementation("net.createmod.ponder:Ponder-NeoForge-${minecraft_version}:${ponder_version}")

    // KubeJS
    implementation("dev.latvian.mods:kubejs-neoforge:${kubejs_version}") { transitive = false }
    implementation("dev.latvian.mods:rhino-neoforge:${rhino_version}")

    // Nature's Aura
    implementation("maven.modrinth:natures-aura:${natures_aura_version}")

    // Pneumaticcraft
    implementation("me.desht.pneumaticcraft:pneumaticcraft-repressurized:${pneumaticcraft_version}")

    // Blood Magic
//    implementation("com.wayoftime.bloodmagic:BloodMagic:${blood_magic_version}")

    // Embers Rekindled
    // TODO 1.21 not available
//    implementation("maven.modrinth:embers:${embers_rekindled_version}")

    // Mana and Artifice
//    implementation("maven.modrinth:mana-and-artifice:${mana_and_artifice_version}")

    // Jade
    implementation("maven.modrinth:jade:${jade_version}")

    // Ars Nouveau
    implementation("com.hollingsworth.ars_nouveau:ars_nouveau-${minecraft_version}:${ars_nouveau_version}")
}