dependencies {
    implementation "net.neoforged:neoforge:${neo_version}"

    // lombok
    compileOnly 'org.projectlombok:lombok:1.18.30'
    annotationProcessor 'org.projectlombok:lombok:1.18.30'

    // LDLib2
    implementation("com.lowdragmc.ldlib2:ldlib2-neoforge-${minecraft_version}:${ldlib2_version}:all")

    // JEI
    compileOnly("mezz.jei:jei-${minecraft_version}-common-api:${jei_version}") { transitive = false }
    compileOnly("mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}") { transitive = false }
    localImplementation("mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}")

    // REI
    compileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin-neoforge:${rei_version}")
    compileOnly("me.shedaniel:RoughlyEnoughItems-api-neoforge:${rei_version}")
    compileOnly("me.shedaniel:RoughlyEnoughItems-neoforge:${rei_version}")

    // EMI
    compileOnly("dev.emi:emi-neoforge:${emi_version}:api")
    compileOnly("dev.emi:emi-neoforge:${emi_version}")

    // Geckolib
    localImplementation("software.bernie.geckolib:geckolib-neoforge-${minecraft_version}:${geckolib_version}")
    localImplementation("com.eliotlash.mclib:mclib:20")

    // Photon
    localImplementation("com.lowdragmc.photon:photon-neoforge-${minecraft_version}:${photon2_version}") { transitive = false }

    // Botania
//    compileOnly("vazkii.botania:botania-neoforge-${minecraft_version}:${botania_version}:api")
//    localImplementation("vazkii.botania:botania-neoforge-${minecraft_version}:${botania_version}")
    runtimeOnly("top.theillusivec4.curios:curios-neoforge:${curios_version}")
    runtimeOnly("vazkii.patchouli:Patchouli:${patchouli_version}")

    // Mekanism
    compileOnly("mekanism:Mekanism:${mekanism_version}:api")
    localImplementation("mekanism:Mekanism:${mekanism_version}") // Mekanism
    runtimeOnly("mekanism:Mekanism:${mekanism_version}:additions")// Mekanism: Additions
    runtimeOnly("mekanism:Mekanism:${mekanism_version}:generators")// Mekanism: Generators
    runtimeOnly("mekanism:Mekanism:${mekanism_version}:tools")// Mekanism: Tools

    // GTM
//    compileOnly("com.gregtechceu.gtceu:gtceu-${minecraft_version}:${gtm_version}") { transitive = false }
//    compileOnly("com.tterrag.registrate:Registrate:${registrate_version}")

    // Create
    localImplementation("com.simibubi.create:create-${minecraft_version}:${create_version}:slim") { transitive = false }
    localImplementation("net.createmod.ponder:ponder-neoforge:${ponder_version}+mc${minecraft_version}")
    compileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraft_version}:${flywheel_version}")
    runtimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraft_version}:${flywheel_version}")
    localImplementation("com.tterrag.registrate:Registrate:${registrate_version}")

    // KubeJS
    localImplementation("dev.latvian.mods:kubejs-neoforge:${kubejs_version}")  {
        exclude(group: "dev.architectury")
    }

    // Nature's Aura
    localImplementation("maven.modrinth:natures-aura:${natures_aura_version}")

    // Pneumaticcraft
    localImplementation("me.desht.pneumaticcraft:pneumaticcraft-repressurized:${pneumaticcraft_version}")

    // Blood Magic
//    implementation("com.wayoftime.bloodmagic:BloodMagic:${blood_magic_version}")

    // Embers Rekindled
    // TODO 1.21 not available
//    implementation("maven.modrinth:embers:${embers_rekindled_version}")

    // Mana and Artifice
//    implementation("maven.modrinth:mana-and-artifice:${mana_and_artifice_version}")

    // Jade
    localImplementation("maven.modrinth:jade:${jade_version}")

    // Ars Nouveau
//    localImplementation("com.hollingsworth.ars_nouveau:ars_nouveau-${minecraft_version}:${ars_nouveau_version}")

    // AE2
    localImplementation("org.appliedenergistics:appliedenergistics2:${ae2_version}")
}