org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
minecraft_version_range=[1.21,1.22)
loader_version=2
neo_version=21.1.219
neoforge_version_range=[21.1.217,)
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17


## Mod Properties
mod_id=mbd2
mod_name=Multiblocked2
mod_license=LGPL-3.0 license
mod_version=21.1.1
maven_group=com.lowdragmc.multiblocked2
mod_authors=KilaBash
mod_url=https://github.com/Low-Drag-MC/Multiblocked2
mod_description=Multiblocked2 is a mod that allows you to create multiblocks in Minecraft.

## Dependencies version
ldlib2_version=2.2.38
ldlib2_version_range=[2.2.38,)
# kilagraph - https://github.com/Low-Drag-MC/KilaGraph
kilagraph_version=21.1.0.13
kilagraph_version_range=[21.1.0.12,)
# kilagraph - https://github.com/Low-Drag-MC/Photon
photon2_version=2.2.5
photon2_version_range=[2.2.5,)
jei_version=19.39.0.368
rei_version=16.0.799
emi_version=1.1.22+1.21.1
kubejs_version=2101.7.2-build.226
geckolib_version=4.8.4
photon_version=1.0.7.b
botania_version=454-SNAPSHOT
curios_version=9.2.2+1.21.1
patchouli_version=1.21.1-94-NEOFORGE-SNAPSHOT
mekanism_version=1.21.1-10.7.19.85
#gtm_version=1.6.4-SNAPSHOT
create_version=6.0.10-280
ponder_version=1.0.82
flywheel_version=1.0.6
registrate_version=MC1.21-1.3.0+67
natures_aura_version=41.9
pneumaticcraft_version=8.2.20+mc1.21.1
embers_rekindled_version=1.20.1-1.3.9
mana_and_artifice_version=3.1.0.1
ars_nouveau_version=5.5.1.978
ae2_version=19.2.17
jade_version=15.9.4+neoforge
