modLoader="javafml" #mandatory
loaderVersion = "[${loader_version},)"
license="${mod_license}"

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
authors="${mod_authors}" #optional
description='''${mod_description}'''
logoFile = "icon.png"
issueTrackerURL = "https://github.com/Low-Drag-MC/Multiblocked2/issues"

[[mixins]]
config="$mixins.{mod_id}.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="${forge_version_range}" #mandatory
ordering="NONE"
side="BOTH"# Here's another dependency

[[dependencies.${mod_id}]]
modId="minecraft"
type = "required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="ldlib"
type = "required"
versionRange="${ldlib_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="create"
type = "optional"
versionRange="[6.0.0,)"
ordering="NONE"
side="BOTH"
